### PR TITLE
COMPASS-2460 - Add Babel to Hadron Document Build

### PR DESCRIPTION
**Pull request by aherlihy**

### CODE REVIEW

**Comment by durran** [comment]
Looking at the output in `lib` this isn't compiling to ES5. I think the babel preset needs to be `es2015` instead of `react`

**Comment by aherlihy** [comment]
@durran Ok so --- two questions.

1. the code is definitely different, but I can't tell what's es2015 and what's not by looking at the compiled source. What's your giveaway?

2. do I also need to modify https://github.com/mongodb-js/hadron-document/blob/5579d79e7fb7846cae44abaeac673046ddd3e47d/package.json#L21 ?

3. the linter is failing when I commit because it's looking at the lib folder, which it shouldn't, but that's just using the mongodb-js-precommit. Should I remove the lib folder from git since it's getting generated anyway?

**Comment by durran** [comment]
I think you can remove the `--presets react` bit since the .babelrc seems to take preference over the command line args. I'd test that and see if that holds true but I suspect so.

As for the linter, you can either 1) .gitignore the lib directory or 2) Create an .eslintignore file in the root with `lib/**/*.*` in it. I personally don't have a preference either way. hadron-react-* does the later.

**Comment by durran** [comment]
👍

**Pull request merged**
